export const F = {
  id: 'id',
  status: 'status',
  title: 'title',
  description: 'description',
  lat: 'lat',
  lng: 'lng',
  street: 'street',
  suburb: 'suburb',
  state: 'state',
  postcode: 'postcode',
  start_date: 'start_date',
  end_date: 'end_date',
  open_from: 'open_from',
  open_to: 'open_to',
  tags: 'tags',
  scare_level: 'scare_level',
  photo_url: 'photo_url',
} as const;
